name: example
description: Demonstrates how to use the immutable_proto plugin.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  immutable_proto:
    path: ../immutable_proto

dev_dependencies:
  build_runner: '>=0.9.0 <1.6.7'
  immutable_proto_generator:
    path: ../immutable_proto_generator
