name: immutable_proto_generator
description: Dart packages for generating immutable classes from Protocol Buffers
version: 0.0.1
homepage: https://github.com/JonasWanke/immutable_proto/tree/master/immutable_proto_generator
author: Jonas Wanke <contact@wanke.dev>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: ^1.1.7
