name: immutable_proto
description: Dart packages for generating immutable classes from Protocol Buffers
version: 0.0.1
homepage: https://github.com/JonasWanke/immutable_proto/tree/master/immutable_proto
author: Jonas Wanke <contact@wanke.dev>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  protobuf: ^0.13.15
  kt_dart: ^0.6.2
  meta: ^1.1.7
