name: immutable_proto
description: Automatically generates an immutable class for a ProtoBuf
version: 0.0.4
homepage: https://github.com/JonasWanke/immutable_proto/tree/master/immutable_proto
author: Jonas Wanke <contact@wanke.dev>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.7
  
dev_dependencies:
  pedantic: ^1.0.0
