name: example
description: Demonstrates how to use the immutable_proto plugin.

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  protobuf: ^1.0.0
  meta: ^1.1.7
  immutable_proto: ^0.0.5+1

dev_dependencies:
  build_runner: ^1.8.1
  immutable_proto_generator:
    path: ../../immutable_proto_generator
